/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.leachryan.patterns

import dev.leachryan.patterns.core.context.RollContext
import dev.leachryan.patterns.core.model.Dice
import dev.leachryan.patterns.core.strategies.DamageRollStrategy
import dev.leachryan.patterns.core.strategies.RollStrategy
import dev.leachryan.patterns.core.strategies.SkillCheckStrategy

class Client(private val strategy: RollStrategy) {
    fun executeRolls() {
        val context = RollContext(strategy)
        context.execute()
    }
}

fun main() {
    val d20 = Dice(20)
    val skillCheckStrategy = SkillCheckStrategy(15, d20)
    val skillCheckClient = Client(skillCheckStrategy)
    skillCheckClient.executeRolls()

    val d12 = Dice(12)
    val damageRollStrategy = DamageRollStrategy(d12)
    val damageRollClient = Client(damageRollStrategy)
    damageRollClient.executeRolls()
}
